site_name: 'FluentTesting'

nav:
  - Home: index.md
  - Mocking: mocking.md
  - Dotnet: dotnet.md
  - ASP:
      - ASP: asp/asp.md
      - Extensions: asp/aspExtensions.md
  - Azurite:
      - Blob: blob/blob.md
      - AzureExplorer: blob/azureExplorer.md
  - Kafka:
      - Kafka: kafka/kafka.md
      - AKHQ: kafka/akhq.md
  - RabbitMq:
     - RabbitMQ: rabbit/rabbit.md
     - RabbitMQ Manager: rabbit/rabbitManager.md
     - Samples: rabbit/rabbitSamples.md 
  - MsSql: 
      - SQL: sql/sql.md
      - Adminer: sql/adminer.md
      - Extensions: sql/extensions.md
  - Elasticsearch: 
      - Elastic: elastic/elastic.md
      - Kibana: elastic/kibana.md
  - Redis:
      - Redis: redis/redis.md
      - RedisInsight: redis/redisInsight.md
  - Mongo: 
      - Mongo: mongo/mongo.md
      - MongoExpress: mongo/mongoExpress.md
  - Samples: samples.md
  - FAQ: faq/faq.md

plugins:
  - codeinclude 
  - search

theme:
  name: flatly
  highlightjs: true
  features:
    - instant
    - tabs

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.toc
  - fenced_code
  # - pymdownx.highlight:
  #     extend_pygments_lang:
  #       - name: csharp
  #       - lang: csharp
  #       - options:
  #         - startinline: true
  #     linenums: true
  #     linenums_style: pymdownx-inline