name: Bug Report
description: Report an issue or a bug in the application
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please provide as much detail as possible below.

  - type: input
    id: title
    attributes:
      label: Title
      description: A short description of the issue.
      placeholder: Login button not working

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the issue.
      placeholder: What happened? What did you expect to happen?

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Open the app
        2. Click on the "Login" button
        3. Error message appears

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: The user should log in successfully.

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information? (e.g., screenshots, logs, etc.)
      placeholder: Include a screenshot or a link to logs, if applicable.
