// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by AvroDotnet, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Alza.KafkaTest
{
	using System;
	using Alza.Client.Kafka.Common;
	using Confluent.Kafka;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("AvroDotnet", "1.11.1")]
	public partial class SomeAwesomeAvro : global::Avro.Specific.ISpecificRecord, IKafkaMessage
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"SomeAwesomeAvro\",\"namespace\":\"Alza.KafkaTest\",\"fields\":[" +
				"{\"name\":\"SomeDate\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"SomeStri" +
				"ng\",\"type\":\"string\"}]}");
		private System.DateTime _SomeDate;
		private string _SomeString;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SomeAwesomeAvro._SCHEMA;
			}
		}
		public System.DateTime SomeDate
		{
			get
			{
				return this._SomeDate;
			}
			set
			{
				this._SomeDate = value;
			}
		}
		public string SomeString
		{
			get
			{
				return this._SomeString;
			}
			set
			{
				this._SomeString = value;
			}
		}
		public Headers Headers { get; set; }
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.SomeDate;
			case 1: return this.SomeString;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.SomeDate = (System.DateTime)fieldValue; break;
			case 1: this.SomeString = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
