name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - develop
  pull_request:
    branches:
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Get Version from csproj
        id: get_version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" src/FluentTesting/common.props)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Set Final Version
        id: set_final_version
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            FINAL_VERSION="${{ env.VERSION }}-pr-${GITHUB_SHA::8}"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            FINAL_VERSION="${{ env.VERSION }}-beta-${GITHUB_SHA::8}"
          else
            FINAL_VERSION="${{ env.VERSION }}"
          fi
          echo "FINAL_VERSION=${FINAL_VERSION}" >> $GITHUB_ENV
          echo "Final version set: $FINAL_VERSION"

      - name: Pack
        run: dotnet pack --configuration Release --output ./output /p:PackageVersion=${{ env.FINAL_VERSION }}

      - name: Publish to NuGet
        if: ${{ github.event_name != 'pull_request' }}
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Publish to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: dotnet nuget push ./output/*.nupkg --api-key ${{ secrets.CI_CD }} --source "https://nuget.pkg.github.com/Rades98/index.json" --skip-duplicate
