name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Change to your required .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test  # Adjust this command based on your testing framework
